import {
  EmitContext,
  emitFile,
  Model,
  Interface,
  Namespace,
  Program,
} from "@typespec/compiler";
import {
  collectServices,
  RpcInfo,
  ServiceInfo,
  toSnakeCase,
  isStreamOp,
} from "@speconn/typespec-emitter-core";

export type EmitterOptions = {
  "emitter-output-dir": string;
};

async function emitDart(program: Program, services: ServiceInfo[], outputDir: string): Promise<void> {
  const promises: Promise<void>[] = [];

  for (const svc of services) {
    if (svc.rpcs.length === 0) continue;
    const snake = toSnakeCase(svc.serviceName);
    const typesFile = `${snake}_types.dart`;
    const reqType = (rpc: RpcInfo) => rpc.inputType?.name ?? "Object";
    const resType = (rpc: RpcInfo) => rpc.outputType?.name ?? "Object";
    const reqCodec = (rpc: RpcInfo) => rpc.inputType ? `${rpc.inputType.name}Codec` : "emptyCodec";
    const resCodec = (rpc: RpcInfo) => rpc.outputType ? `${rpc.outputType.name}Codec` : "emptyCodec";

    // ---- client ----
    const client: string[] = [];
    client.push("// Generated by @speconn/typespec-emitter-dart. DO NOT EDIT.\n");
    client.push("import 'package:speconn/speconn.dart';");
    client.push(`import '${typesFile}';\n`);
    client.push(`class ${svc.serviceName}Client {`);
    for (const rpc of svc.rpcs) {
      client.push(`  final SpeconnClient _${rpc.name};`);
    }
    client.push(`  ${svc.serviceName}Client(String baseUrl, {SpeconnTransport? transport})`);
    const inits = svc.rpcs.map(rpc =>
      `      _${rpc.name} = SpeconnClient(baseUrl, '${rpc.path}', transport: transport)`
    );
    client.push(`      : ${inits.join(",\n        ")};`);
    for (const rpc of svc.rpcs) {
      if (rpc.isStream) {
        client.push(`  Future<StreamResponse<${resType(rpc)}>> ${rpc.name}(${reqType(rpc)} req, {Map<String, String>? headers, int? timeoutMs}) =>`);
        client.push(`      _${rpc.name}.stream(${reqCodec(rpc)}, req, ${resCodec(rpc)}, CallOptions(headers: headers ?? {}, timeoutMs: timeoutMs));`);
      } else {
        client.push(`  Future<Response<${resType(rpc)}>> ${rpc.name}(${reqType(rpc)} req, {Map<String, String>? headers, int? timeoutMs}) =>`);
        client.push(`      _${rpc.name}.call(${reqCodec(rpc)}, req, ${resCodec(rpc)}, CallOptions(headers: headers ?? {}, timeoutMs: timeoutMs));`);
      }
    }
    client.push('}\n');

    promises.push(emitFile(program, { path: `${outputDir}/${snake}.client.dart`, content: client.join("\n") }));
  }
  await Promise.all(promises);
}

export async function $onEmit(context: EmitContext<EmitterOptions>) {
  const services = collectServices(context.program);
  await emitDart(context.program, services, context.emitterOutputDir);
}
